import type { Genre, IndustryContentFormat, IndustryContentReleasePath, IndustryContentRelationship, IndustryContentSourceIntent } from '../../types';

export const INDUSTRY_CONTENT_FORMATS: readonly IndustryContentFormat[] = ['MOVIE', 'SERIES', 'LIMITED_SERIES'];
export const INDUSTRY_CONTENT_GENRES: readonly Genre[] = ['DRAMA', 'ACTION', 'COMEDY', 'ROMANCE', 'THRILLER', 'MYSTERY', 'HORROR', 'SCI_FI', 'ADVENTURE', 'SUPERHERO', 'ANIMATION', 'CRIME', 'DOCUMENTARY', 'FANTASY', 'BIOPIC', 'SPORTS'];
export const INDUSTRY_CONTENT_SUBGENRES = ['CHARACTER_STUDY', 'CONSPIRACY', 'SURVIVAL', 'FAMILY_SAGA', 'HEIST', 'POLITICAL_INTRIGUE', 'COMING_OF_AGE', 'TECHNO_THRILLER', 'DARK_COMEDY', 'EPIC_QUEST', 'PROCEDURAL', 'SOCIAL_REALISM'] as const;
export const INDUSTRY_CONTENT_TONES = ['GROUNDED', 'TENSE', 'HOPEFUL', 'DARK', 'PLAYFUL', 'EPIC', 'INTIMATE', 'SATIRICAL', 'MELANCHOLIC', 'KINETIC'] as const;
export const INDUSTRY_CONTENT_THEMES = ['IDENTITY', 'LOYALTY', 'AMBITION', 'JUSTICE', 'FAMILY', 'POWER', 'REDEMPTION', 'BELONGING', 'SURVIVAL', 'LEGACY', 'TRUTH', 'FREEDOM'] as const;
export const INDUSTRY_CONTENT_SETTINGS = ['METROPOLIS', 'SMALL_TOWN', 'BORDERLAND', 'DEEP_SPACE', 'ROYAL_COURT', 'CORPORATE_WORLD', 'COASTAL_CITY', 'WILDERNESS', 'UNDERWORLD', 'UNIVERSITY', 'FUTURE_COLONY', 'REMOTE_ISLAND'] as const;
export const INDUSTRY_CONTENT_PERIODS = ['CONTEMPORARY', 'NEAR_FUTURE', 'HISTORICAL', 'RETRO_1980S', 'RETRO_1990S', 'DISTANT_FUTURE', 'MYTHIC_PAST'] as const;
export const INDUSTRY_CONTENT_AUDIENCES = ['FAMILY', 'YOUNG_ADULT', 'ADULT_MAINSTREAM', 'PRESTIGE_ADULT', 'GENRE_FANS', 'GLOBAL_FOUR_QUADRANT', 'LOCAL_MAINSTREAM'] as const;
export const INDUSTRY_CONTENT_LANGUAGES = ['ENGLISH', 'HINDI', 'SPANISH', 'KOREAN', 'JAPANESE', 'FRENCH', 'GERMAN', 'PORTUGUESE', 'TAMIL', 'TELUGU'] as const;
export const INDUSTRY_CONTENT_MARKETS = ['NORTH_AMERICA', 'INDIA', 'LATIN_AMERICA', 'EAST_ASIA', 'EUROPE', 'MIDDLE_EAST', 'AFRICA', 'GLOBAL'] as const;
export const INDUSTRY_CONTENT_RELEASE_PATHS: readonly IndustryContentReleasePath[] = ['THEATRICAL_FIRST', 'STREAMING_FIRST', 'HYBRID', 'LIMITED_EVENT'];
export const INDUSTRY_CONTENT_SOURCE_INTENTS: readonly IndustryContentSourceIntent[] = ['ORIGINAL', 'INTERNAL_DEVELOPMENT', 'PLATFORM_ORIGINAL', 'INDIVIDUAL_COMMISSION', 'LICENSED_WORK', 'ACQUIRED_IP', 'SEQUEL', 'PREQUEL', 'REBOOT', 'SPIN_OFF', 'UNIVERSE_ENTRY', 'UNIVERSE_CROSSOVER', 'UNIVERSE_EVENT', 'INHERITED'];
export const INDUSTRY_CONTENT_RELATIONSHIPS: readonly IndustryContentRelationship[] = ['STANDALONE', 'SEQUEL', 'PREQUEL', 'REBOOT', 'SPIN_OFF', 'UNIVERSE_ENTRY', 'UNIVERSE_CROSSOVER', 'UNIVERSE_EVENT', 'FOUND_UNIVERSE'];
