export const PHASE_ONE_ENERGY_COSTS = {
    PRODUCTION_HOUSE_SIGNING: 25,
    STUDIO_ACQUISITION_SIGNING: 25,
    STOCK_CONTROL_TAKEOVER_COMPLETION: 25,
    OUTSIDE_PRODUCER_INVESTMENT_ACCEPT: 25,
    RIGHTS_FINAL_SIGNING: 20,
    GREENLIGHT_OWNED_PROJECT: 15,
    ACQUISITION_STRATEGY_ACTION: 10,
    RIGHTS_STRATEGY_ACTION: 10,
    STOCK_TAKEOVER_ROUTE_ACTION: 15,
    STREAMING_DEAL_ACCEPT: 10,
    RELEASE_STRATEGY_LOCK: 15,
    COLLABORATION_SIGNING: 10,
} as const;

export type PhaseOneEnergyCostKey = keyof typeof PHASE_ONE_ENERGY_COSTS;
