import React from 'react';
import type { LifestyleUiDestination, LifestyleUiDestinationId, LifestyleUiModel } from '../../services/lifestyleUiAdapter';
import { BASE_CSS } from './theme';
import { Icon, Style, cssVar, money, useReveal } from './ui';

interface LifestyleHubScreenProps extends LifestyleUiModel {
  onOpen: (id: LifestyleUiDestinationId) => void;
}

const CSS = `
.lf-head{margin-bottom:15px}.mc-scene{perspective:1500px;margin-top:2px}.mc-card{position:relative;width:100%;aspect-ratio:1.586/1;transform-style:preserve-3d;transition:transform .72s cubic-bezier(.32,.9,.28,1);cursor:pointer;-webkit-tap-highlight-color:transparent}.mc-card.is-back{transform:rotateY(180deg)}.mc-face{position:absolute;inset:0;border-radius:18px;overflow:hidden;backface-visibility:hidden;-webkit-backface-visibility:hidden;box-shadow:inset 0 0 0 1px rgba(255,255,255,.12),inset 0 1px 0 rgba(255,255,255,.1),0 26px 48px -30px #000}.mc-front{display:flex;flex-direction:column;padding:17px 19px 16px;background:radial-gradient(74% 120% at 84% -18%,rgba(255,255,255,.055),transparent 58%),repeating-linear-gradient(114deg,rgba(255,255,255,.028) 0 1px,transparent 1px 3px),linear-gradient(148deg,#272420 0%,#100e0b 44%,#1c1914 100%)}.mc-back{transform:rotateY(180deg);display:flex;flex-direction:column;background:repeating-linear-gradient(114deg,rgba(255,255,255,.022) 0 1px,transparent 1px 3px),linear-gradient(148deg,#211e1a 0%,#0e0c0a 52%,#181512 100%)}.mc-front::after{content:"";position:absolute;top:-30%;bottom:-30%;left:-40%;width:32%;pointer-events:none;background:linear-gradient(90deg,transparent,rgba(255,255,255,.13),transparent);transform:skewX(-18deg);animation:mc-sweep 1.5s cubic-bezier(.4,0,.2,1) .5s both}@keyframes mc-sweep{from{left:-40%}to{left:124%}}
.mc-brand{display:flex;align-items:center}.mc-brand b{font-size:10px;font-weight:800;letter-spacing:.3em;background:linear-gradient(180deg,#ffeab4,#e0a01c 54%,#b07d18);-webkit-background-clip:text;background-clip:text;color:transparent}.mc-net{margin-left:auto;position:relative;width:37px;height:22px}.mc-net i{position:absolute;top:0;width:22px;height:22px;border-radius:50%}.mc-net i:first-child{left:0;background:rgba(248,168,16,.82)}.mc-net i:last-child{right:0;background:rgba(255,92,92,.62);mix-blend-mode:screen}.mc-chiprow{display:flex;align-items:center;gap:12px;margin-top:15px}.mc-chip{width:40px;height:31px;flex:none}.mc-wave{width:18px;height:21px;flex:none;color:rgba(248,168,16,.42)}.mc-num{margin-top:auto}.mc-num span{display:block;margin-bottom:7px;font-size:7px;font-weight:800;letter-spacing:.26em;color:rgba(249,246,239,.3)}.mc-num b{display:block;font-size:29px;font-weight:800;letter-spacing:-.035em;line-height:1;background:linear-gradient(180deg,#fff,#dcd8d0 44%,#a5a19a);-webkit-background-clip:text;background-clip:text;color:transparent;filter:drop-shadow(0 1px 0 rgba(0,0,0,.6));white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mc-foot{display:flex;align-items:flex-end;gap:18px;margin-top:15px}.mc-f{min-width:0}.mc-f span{display:block;font-size:6.5px;font-weight:800;letter-spacing:.22em;color:rgba(249,246,239,.28)}.mc-f b{display:block;margin-top:4px;font-size:12px;font-weight:750;letter-spacing:.1em;text-transform:uppercase;color:rgba(249,246,239,.84);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mc-f.is-r{margin-left:auto;text-align:right;flex:none}
.mc-stripe{height:42px;margin-top:19px;background:linear-gradient(180deg,#000 0%,#191715 34%,#0a0908 68%,#000 100%);box-shadow:inset 0 1px 0 rgba(255,255,255,.1),inset 0 -1px 0 rgba(255,255,255,.07),0 1px 4px rgba(0,0,0,.6)}.mc-sig{display:flex;align-items:center;gap:10px;margin:15px 19px 0;height:31px;border-radius:4px;padding:0 11px;background:repeating-linear-gradient(100deg,#ece6d9 0 7px,#ded7c6 7px 14px)}.mc-sig b{min-width:0;font-size:12.5px;font-weight:600;font-style:italic;color:#2b2518;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mc-sig u{text-decoration:none;margin-left:auto;font-size:7.5px;font-weight:800;letter-spacing:.16em;color:#6e6553}.mc-bf{display:flex;gap:24px;margin:14px 19px 0}.mc-bf div span{display:block;font-size:6.5px;font-weight:800;letter-spacing:.22em;color:rgba(249,246,239,.28)}.mc-bf div b{display:block;margin-top:4px;font-size:15px;font-weight:800;letter-spacing:-.035em;color:var(--c)}.mc-bsplit{display:flex;gap:2px;height:8px;margin:auto 19px 0;border-radius:2px;overflow:hidden}.mc-bsplit i{background:var(--c);transition:flex-grow .8s cubic-bezier(.2,.8,.2,1)}.mc-bleg{display:flex;gap:13px;margin:9px 19px 15px}.mc-bl{display:flex;align-items:center;gap:5px;font-size:7.5px;font-weight:800;letter-spacing:.1em;color:var(--faint)}.mc-bl i{width:6px;height:6px;flex:none;border-radius:2px;background:var(--c)}.mc-bl b{color:var(--c)}.mc-hint{display:flex;align-items:center;justify-content:center;gap:6px;width:100%;margin-top:11px;font-size:8px;font-weight:800;letter-spacing:.18em;color:var(--ghost)}
.lf-row{width:100%;margin-top:8px;padding:13px;border-radius:19px;text-align:left;display:flex;align-items:center;gap:13px;background:var(--card);box-shadow:inset 0 0 0 1px var(--line-2);transition:transform .12s ease}.lf-row:active{transform:scale(.99);background:var(--card-2)}.lf-row.is-active{background:color-mix(in srgb,var(--gold) 8%,var(--card));box-shadow:inset 0 0 0 1.5px var(--line-on)}.lf-row.is-locked .lf-row-n,.lf-row.is-locked .lf-row-d{color:var(--faint)}.lf-ic{width:48px;height:48px;flex:none;border-radius:16px;display:grid;place-items:center;color:var(--c);background:color-mix(in srgb,var(--c) 13%,transparent);box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--c) 26%,transparent)}.lf-row.is-active .lf-ic{color:#241606;background:var(--gold);box-shadow:none}.lf-row-t{flex:1;min-width:0}.lf-row-h{display:flex;align-items:center;gap:7px}.lf-row-n{font-size:16px;font-weight:750;letter-spacing:-.025em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.lf-row-h svg{flex:none;color:var(--gold-hi)}.lf-row-d{display:block;margin-top:4px;font-size:11px;font-weight:650;line-height:1.4;color:var(--faint)}.lf-row-b{flex:none;display:flex;align-items:center;gap:9px}.lf-pct{position:relative;width:38px;height:38px;flex:none}.lf-pct svg{position:absolute;inset:0;transform:rotate(-90deg)}.lf-pct b{position:absolute;inset:0;display:grid;place-items:center;font-size:9.5px;font-weight:800;letter-spacing:-.03em;color:var(--c)}.lf-lock{display:flex;align-items:center;gap:5px;padding:6px 9px;border-radius:9px;font-size:8.5px;font-weight:800;letter-spacing:.13em;color:var(--faint);background:rgba(255,255,255,.04);box-shadow:inset 0 0 0 1px var(--hair)}
@media(max-width:374px){.ae-scroll{padding-left:12px;padding-right:12px}.mc-front{padding:14px 16px 13px}.mc-chiprow{margin-top:10px}.mc-num b{font-size:24px}.mc-foot{margin-top:10px}.mc-f b{font-size:10px}.mc-stripe{height:35px;margin-top:16px}.mc-sig{margin-top:11px}.mc-bf{margin-top:10px}.mc-bleg{margin-bottom:11px;gap:8px}.mc-bl{font-size:6.5px}.lf-row{padding:11px;gap:10px}.lf-ic{width:42px;height:42px;border-radius:14px}.lf-row-n{font-size:14px}.lf-row-d{font-size:9.5px}.lf-row-b{gap:5px}.lf-lock{padding-left:6px;padding-right:6px;font-size:7px}.lf-pct{width:34px;height:34px}}
`;

const SECTIONS: Array<{ kind: LifestyleUiDestination['kind']; label: string; note: string }> = [
  { kind: 'venture', label: 'Ventures', note: 'What earns' },
  { kind: 'spending', label: 'Spending', note: 'What burns' },
];

const shortMoney = (value: number) => {
  const absolute = Math.abs(value);
  if (absolute >= 1e9) return `$${(value / 1e9).toFixed(absolute >= 1e10 ? 0 : 1)}B`;
  if (absolute >= 1e6) return `$${(value / 1e6).toFixed(absolute >= 1e8 ? 0 : 1)}M`;
  if (absolute >= 1e3) return `$${Math.round(value / 1e3)}K`;
  return `$${Math.round(value)}`;
};

export default function LifestyleHubScreen(props: LifestyleHubScreenProps) {
  const reveal = useReveal();
  const [back, setBack] = React.useState(false);
  const total = Math.max(1, props.liquidCash + props.assets + props.equity);
  const parts = [
    { key: 'cash', short: 'CASH', value: props.liquidCash, color: 'var(--gold-hi)' },
    { key: 'assets', short: 'ASSETS', value: props.assets, color: 'var(--acting)' },
    { key: 'equity', short: 'EQUITY', value: props.equity, color: 'var(--money)' },
  ];
  const progressRadius = 16;
  const progressLength = 2 * Math.PI * progressRadius;

  return <div className="ae" data-ui="actor-empire-lifestyle-overhaul"><Style css={BASE_CSS} /><Style css={CSS} /><div className="ae-bg" /><div className="ae-scroll">
    <header className="lf-head ae-in"><h1 className="ae-h1">{props.title}</h1><p className="ae-sub">Where the money sits and what it can become</p></header>
    <div className="mc-scene ae-in" style={cssVar('--d', '.04s')}><button type="button" className={`mc-card${back ? ' is-back' : ''}`} onClick={() => setBack(value => !value)} aria-label={back ? 'Show the front of the card' : 'Show the breakdown on the back'}>
      <div className="mc-face mc-front"><div className="mc-brand"><b>ACTOR EMPIRE</b><span className="mc-net" aria-hidden="true"><i /><i /></span></div><div className="mc-chiprow"><svg className="mc-chip" viewBox="0 0 40 31" aria-hidden="true"><rect x=".7" y=".7" width="38.6" height="29.6" rx="5" fill="#dfa01d" /><rect x="11.6" y="6.4" width="16.8" height="18.2" rx="2.8" fill="none" stroke="#0f0b06" strokeWidth="1.3" opacity=".5" /><path d="M.7 10.7h10.9M28.4 10.7h10.9M.7 20.3h10.9M28.4 20.3h10.9M15.8.7v5.7M24.2.7v5.7M15.8 30.3v-5.7M24.2 30.3v-5.7" fill="none" stroke="#0f0b06" strokeWidth="1.3" opacity=".5" /></svg><svg className="mc-wave" viewBox="0 0 18 21" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M3.2 6.8a7 7 0 0 1 0 7.4M7.9 4a12 12 0 0 1 0 13M12.6 1.2a17 17 0 0 1 0 18.6" /></g></svg></div><div className="mc-num"><span>LIQUID CASH</span><b>{money(Math.round(props.liquidCash * reveal))}</b></div><div className="mc-foot"><span className="mc-f"><span>CARDHOLDER</span><b>{props.holder}</b></span><span className="mc-f is-r"><span>VALID THRU</span><b>{props.validThru}</b></span></div></div>
      <div className="mc-face mc-back"><div className="mc-stripe" /><div className="mc-sig"><b>{props.holder}</b><u>AUTHORISED</u></div><div className="mc-bf"><div style={cssVar('--c', 'var(--acting)')}><span>ASSETS</span><b>{props.assets ? shortMoney(props.assets) : '~$0'}</b></div><div style={cssVar('--c', 'var(--money)')}><span>EQUITY</span><b>{props.equity ? shortMoney(props.equity) : '~$0'}</b></div></div><div className="mc-bsplit">{parts.map(part => <i key={part.key} style={{ flexGrow: Math.max(0, part.value / total), ...cssVar('--c', part.color) }} />)}</div><div className="mc-bleg">{parts.map(part => <span className="mc-bl" key={part.key} style={cssVar('--c', part.color)}><i />{part.short} <b>{Math.round(part.value / total * 100)}%</b></span>)}</div></div>
    </button><span className="mc-hint"><Icon name={back ? 'card' : 'chevronRight'} size={11} sw={2.2} />{back ? 'TAP THE CARD TO TURN IT BACK' : 'TAP THE CARD FOR THE BREAKDOWN'}</span></div>
    {SECTIONS.map(section => { const destinations = props.destinations.filter(destination => destination.kind === section.kind); return destinations.length ? <section key={section.kind}><div className="ae-sec"><span className="ae-lab">{section.label}</span><span className="ae-sec-rule" /><span className="ae-lab">{section.note}</span></div>{destinations.map(destination => <button key={destination.id} className={`lf-row${destination.active ? ' is-active' : ''}${destination.locked ? ' is-locked' : ''}`} style={cssVar('--c', destination.color)} onClick={() => props.onOpen(destination.id)} aria-label={destination.name}><span className="lf-ic"><Icon name={destination.icon} size={22} /></span><span className="lf-row-t"><span className="lf-row-h"><span className="lf-row-n">{destination.name}</span>{destination.active && <Icon name="star" size={13} />}</span><span className="lf-row-d">{destination.note}</span></span><span className="lf-row-b">{destination.progress !== undefined && <span className="lf-pct"><svg viewBox="0 0 38 38"><circle cx="19" cy="19" r={progressRadius} fill="none" stroke="rgba(255,255,255,.12)" strokeWidth="3" /><circle cx="19" cy="19" r={progressRadius} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeDasharray={progressLength} strokeDashoffset={progressLength * (1 - destination.progress / 100 * reveal)} style={{ color: destination.color }} /></svg><b>{Math.round(destination.progress * reveal)}%</b></span>}{destination.locked && <span className="lf-lock"><Icon name="lock" size={10} sw={2.2} />{destination.locked}</span>}<Icon name="chevronRight" size={16} sw={2.2} /></span></button>)}</section> : null; })}
  </div></div>;
}
